name: Unzip and Deploy Static Site

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Unzip and deploy static site
        run: |
          # Unzip the file
          unzip luviumcapital.com-14.zip -d temp_extract
          
          # Remove old files (keep .github, CNAME, and the zip)
          find . -maxdepth 1 ! -name '.' ! -name '..' ! -name '.git' ! -name '.github' ! -name 'CNAME' ! -name 'luviumcapital.com-14.zip' ! -name 'temp_extract' -exec rm -rf {} +
          
          # Move extracted contents to root (handle nested directories)
          if [ -d "temp_extract/luviumcapital.com" ]; then
            # If there's a luviumcapital.com subdirectory, move its contents
            mv temp_extract/luviumcapital.com/* .
            mv temp_extract/luviumcapital.com/.[!.]* . 2>/dev/null || true
          else
            # Otherwise, move all contents directly
            mv temp_extract/* .
            mv temp_extract/.[!.]* . 2>/dev/null || true
          fi
          
          # Clean up
          rm -rf temp_extract
          rm luviumcapital.com-14.zip
          
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy static site from luviumcapital.com-14.zip"
          git push
